name: CI Workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-containers:
    name: Build Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-2019, windows-2022]
        include:
        - os: ubuntu-latest
          file: Dockerfile.linux
        - os: windows-2019
          file: Dockerfile.windows
        - os: windows-2022
          file: Dockerfile.windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -f ${{ matrix.file }} --tag adventureworks-app:$(date +%s) .
