name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: windows-2019
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . -t phillispj/adventurworks-app:${{ github.event.release.tag_name }}
          docker push phillispj/adventurworks-app:${{ github.event.release.tag_name }}
          